OPENAI_API_KEY = "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"
ASSISTANT_ID = "asst_E80fqsP0WMJrkYuBs15WbF7x"